### ISSUE TITLE
保存配置报错

### ISSUE THREAD

**Issue by heby** [iview/vue-cli-plugin-iview#1]
报错信息如下
```
Invoking generator for vue-cli-plugin-iview...
 ERROR  Error: Line 13: Unexpected token (
Error: Line 13: Unexpected token (
    at ErrorHandler.constructError (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:5028:27)
    at Parser.unexpectedTokenError (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:1985:39)
    at Parser.throwUnexpectedToken (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:1995:21)
    at Parser.parseImportDeclaration (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:4833:23)
    at Parser.parseStatementListItem (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:3373:39)
    at Parser.parseBlock (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:3405:30)
    at Parser.parseStatement (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:4109:39)
    at Parser.parseIfClause (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:3657:22)
    at Parser.parseIfStatement (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\esprima\dist\esprima.js:3672:32)
```

**Comment by icarusion** [comment]
具体配置了什么

**Comment by heby** [comment]
在vue-cli管理页面，从plugins里搜索安装vue-cli-plugin-iview，按默认步骤点击安装，然后安装完成会出现iview的配置选项页面，配置是默认的，然后保存就会出现以上错误。

**Comment by icarusion** [comment]
我这边可以，无法复现。

**Comment by heby** [comment]
我是在之前的项目上安装的，全新配置一个项目没报这个错。
